name: CI

on:
  push:
    branches:
      - develop
      - 'release/**'
  pull_request:
    branches:
      - develop
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Verify Checkstyle
      run: mvn checkstyle:check

    - name: Run unit tests
      run: mvn test

    - name: Verify JaCoCo 100% branch coverage
      run: mvn jacoco:check
